#!/bin/bash

if [ "$1" = "install" -o "$1" = "upgrade" ]
then
	if ischroot; then exit 0; fi
	if ! mountpoint /boot >/dev/null 2>&1; then echo "/boot is not mounted!"; exit 1; fi
	touch /boot/testrw
	if [ $? != 0 ]
	then
	    mount -o remount,ro /boot
	    fsck /boot
	else
	    rm -f /boot/testrw
	fi

	# This prevents vfat symlink errors
	rm -rf /boot/start_x.elf /boot/start.elf /boot/start_cd.elf /boot/fixup_x.dat /boot/fixup.dat /boot/fixup_cd.dat /boot/bootcode.bin
fi
