#!/bin/sh -e

version="$1"
if [ -f "/boot/config.txt" ]; then
  sed -i "/initramfs/c\initramfs initrd.img-${version} followkernel" /boot/config.txt 
fi
echo $version > /boot/kernel.release

# remove old kernel
#x=$(dpkg --list | egrep -i --color 'linux-image|linux-headers|linux-firmware-image' | grep ^rc | awk '{print $2}')
#apt-get --purge remove $x
